### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by DataTables** [fabiospampinato/cash#346]
### Current behavior

I'm having problems building cash at the moment with the latest from github:

```
git clone https://github.com/fabiospampinato/cash.git
cd cash
npm install
npm run dev
```

Results in:

```

> cash-dom@8.0.0 dev /home/vagrant/xxtmp/cash
> npm run build:dev && npm run watch:dev


> cash-dom@8.0.0 build:dev /home/vagrant/xxtmp/cash
> pacco build-javascript -e development

[11:09:28] Starting 'build-javascript'...
dist/cash.ts(428,44): error TS2538: Type 'Record<string, any>' cannot be used as an index type.
dist/cash.ts(759,19): error TS2349: This expression is not callable.
  Not all constituents of type 'string | PluckCallback<U[0]>' are callable.
    Type 'string' has no call signatures.
dist/cash.ts(765,24): error TS2538: Type 'PluckCallback<U[0]>' cannot be used as an index type.
dist/cash.ts(917,3): error TS2322: Type 'string | number' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.
dist/cash.ts(959,33): error TS2345: Argument of type 'string | Record<string, string | number>' is not assignable to parameter of type 'string'.
  Type 'Record<string, string | number>' is not assignable to type 'string'.
dist/cash.ts(963,19): error TS2538: Type 'Record<string, string | number>' cannot be used as an index type.
dist/cash.ts(1117,11): error TS2322: Type 'string' is not assignable to type '"outerWidth" | "innerHeight"'.
dist/cash.ts(1170,36): error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.
dist/cash.ts(1441,46): error TS2345: Argument of type 'string | EventCallback' is not assignable to parameter of type 'string'.
  Type 'EventCallback' is not assignable to type 'string'.
dist/cash.ts(1561,29): error TS2339: Property 'parentNode' does not exist on type 'EventTarget'.
dist/cash.ts(1647,20): error TS2345: Argument of type 'string | Record<string, EventCallback>' is not assignable to parameter of type 'string'.
  Type 'Record<string, EventCallback>' is not assignable to type 'string'.
dist/cash.ts(1716,49): error TS2339: Property '___ot' does not exist on type 'string | Event'.
  Property '___ot' does not exist on type 'string'.
dist/cash.ts(1718,24): error TS2339: Property 'type' does not exist on type 'string | Event'.
  Property 'type' does not exist on type 'string'.
dist/cash.ts(1720,17): error TS2339: Property '___ot' does not exist on type 'string | Event'.
  Property '___ot' does not exist on type 'string'.
dist/cash.ts(1722,24): error TS2339: Property 'type' does not exist on type 'string | Event'.
  Property 'type' does not exist on type 'string'.
dist/cash.ts(1726,25): error TS2345: Argument of type 'string | Event' is not assignable to parameter of type 'Event'.
  Type 'string' is not assignable to type 'Event'.
dist/cash.ts(1745,12): error TS2339: Property 'multiple' does not exist on type 'EleLoose'.
dist/cash.ts(1745,28): error TS2339: Property 'options' does not exist on type 'EleLoose'.
dist/cash.ts(1745,38): error TS2322: Type 'Ele[]' is not assignable to type 'string | string[]'.
  Type 'Ele[]' is not assignable to type 'string[]'.
    Type 'Ele' is not assignable to type 'string'.
      Type 'Element' is not assignable to type 'string'.
dist/cash.ts(1745,71): error TS2339: Property 'options' does not exist on type 'EleLoose'.
dist/cash.ts(1747,14): error TS2339: Property 'value' does not exist on type 'EleLoose'.
dist/cash.ts(1781,16): error TS2339: Property 'elements' does not exist on type 'EleLoose'.
dist/cash.ts(1783,16): error TS2339: Property 'disabled' does not exist on type 'EleLoose'.
dist/cash.ts(1783,33): error TS2339: Property 'name' does not exist on type 'EleLoose'.
dist/cash.ts(1783,94): error TS2339: Property 'type' does not exist on type 'EleLoose'.
dist/cash.ts(1783,129): error TS2339: Property 'type' does not exist on type 'EleLoose'.
dist/cash.ts(1783,144): error TS2339: Property 'checked' does not exist on type 'EleLoose'.
dist/cash.ts(1793,38): error TS2339: Property 'name' does not exist on type 'EleLoose'.
dist/cash.ts(1827,26): error TS2339: Property 'multiple' does not exist on type 'EleLoose'.
dist/cash.ts(1827,42): error TS2339: Property 'options' does not exist on type 'EleLoose'.
dist/cash.ts(1829,45): error TS2339: Property 'type' does not exist on type 'EleLoose'.
dist/cash.ts(1835,20): error TS2339: Property 'options' does not exist on type 'EleLoose'.
dist/cash.ts(1843,13): error TS2339: Property 'checked' does not exist on type 'EleLoose'.
dist/cash.ts(1843,46): error TS2339: Property 'value' does not exist on type 'EleLoose'.
dist/cash.ts(1849,11): error TS2339: Property 'value' does not exist on type 'EleLoose'.
dist/cash.ts(2121,44): error TS2345: Argument of type 'Element' is not assignable to parameter of type 'EleLoose'.
  Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 106 more.
dist/cash.ts(2123,35): error TS2339: Property 'offsetParent' does not exist on type 'Element'.
dist/cash.ts(2162,101): error TS2345: Argument of type 'Element' is not assignable to parameter of type 'EleLoose'.
  Type 'Element' is not assignable to type 'HTMLElement'.
dist/cash.ts(2164,7): error TS2740: Type 'Node & ParentNode' is missing the following properties from type 'Element': assignedSlot, attributes, classList, className, and 64 more.
dist/cash.ts(2221,79): error TS2551: Property 'contentDocument' does not exist on type 'EleLoose'. Did you mean 'ownerDocument'?
dist/cash.ts(2221,133): error TS2339: Property 'content' does not exist on type 'EleLoose'.
dist/cash.ts(2316,38): error TS2345: Argument of type 'Node' is not assignable to parameter of type 'EleLoose'.
  Type 'Node' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 182 more.
dist/cash.ts(2575,24): error TS2345: Argument of type '((i: number, ele: EleLoose) => number) | ((i: number, ele: EleLoose) => boolean)' is not assignable to parameter of type 'Comparator'.
  Type '(i: number, ele: EleLoose) => number' is not assignable to type 'Comparator'.
    Type '(i: number, ele: EleLoose) => number' is not assignable to type '(this: EleLoose, index: number, ele: EleLoose) => boolean'.
      Type 'number' is not assignable to type 'boolean'.
/home/vagrant/xxtmp/cash/node_modules/typescript/lib/lib.dom.d.ts(5524,11): error TS2430: Interface 'FocusEvent' incorrectly extends interface 'UIEvent'.
  Types of property 'relatedTarget' are incompatible.
    Type 'EventTarget' is missing the following properties from type 'Node': baseURI, childNodes, firstChild, isConnected, and 44 more.
/home/vagrant/xxtmp/cash/node_modules/typescript/lib/lib.dom.d.ts(10509,11): error TS2430: Interface 'MouseEvent' incorrectly extends interface 'UIEvent'.
  Types of property 'relatedTarget' are incompatible.
    Type 'EventTarget' is not assignable to type 'Node'.
TypeScript: 45 semantic errors
TypeScript: emit succeeded (with errors)
[Message] TypeScript: Compilation failed
[Stack] Error: TypeScript: Compilation failed
    at Output.mightFinish (/home/vagrant/xxtmp/cash/node_modules/gulp-typescript/release/output.js:130:43)
    at /home/vagrant/xxtmp/cash/node_modules/gulp-typescript/release/output.js:65:22
[11:09:37] Finished 'build-javascript' after 9s

> cash-dom@8.0.0 watch:dev /home/vagrant/xxtmp/cash
> pacco watch-javascript -e development

[11:09:38] Starting 'watch-javascript'...
[11:09:38] Finished 'watch-javascript' after 38ms
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch 'src'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1346:11)
    at createFsWatchInstance (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqCallback.oncomplete (fs.js:167:5)
Emitted 'error' event on Domain instance at:
    at FSWatcher.EventEmitter.emit (domain.js:500:12)
    at FSWatcher._handleError (/home/vagrant/xxtmp/cash/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/vagrant/xxtmp/cash/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:167:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: 'src',
  filename: 'src',
  domainEmitter: FSWatcher {
    _events: [Object: null prototype] {
      add: [Function: debounced],
      change: [Function: debounced],
      unlink: [Function: debounced],
      end: [Function: onend],
      finish: [Function: onfinish],
      close: [Function: onclose]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    _watched: [Object: null prototype] {
      '/home/vagrant/xxtmp/cash': [Object],
      '/home/vagrant/xxtmp/cash/src': [Object],
      '/home/vagrant/xxtmp/cash/src/**/*.ts': [Object],
      '/home/vagrant/xxtmp/cash/src/**/*.js': [Object]
    },
    _closers: [Object: null prototype] {},
    _ignoredPaths: [Object: null prototype] {},
    closed: false,
    _throttled: [Object: null prototype] {},
    _symlinkPaths: [Object: null prototype] {},
    enableBinaryInterval: true,
    _pendingUnlinks: [Object: null prototype] {},
    _isntIgnored: [Function: bound ],
    _emitReady: [Function: bound ],
    options: {
      delay: 200,
      events: [Array],
      ignored: [],
      ignoreInitial: true,
      queue: true,
      persistent: true,
      ignorePermissionErrors: false,
      interval: 100,
      binaryInterval: 300,
      disableGlobbing: false,
      useFsEvents: false,
      usePolling: false,
      atomic: true,
      followSymlinks: true,
      awaitWriteFinish: false
    },
    _userIgnored: [Function: bound anymatch],
    _readyCount: 2,
    [Symbol(kCapture)]: false
  },
  domainThrown: false
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cash-dom@8.0.0 watch:dev: `pacco watch-javascript -e development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cash-dom@8.0.0 watch:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-06-22T11_09_38_116Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cash-dom@8.0.0 dev: `npm run build:dev && npm run watch:dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cash-dom@8.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-06-22T11_09_38_158Z-debug.log
```

### Expected behavior

It would build.

For information, I'm going to make another go at supporting cash with DataTables in place of jQuery. I realise from our discussion before that not all utility functions will be added, but I'm looking to add support for `$.extend(deep, ...)` (#196), `$.each()` with objects (#104) and `$.isPlainObject()` (#334).

Is that suitable? We'll implement the other utilities we need in DataTables itself.

**Comment by fabiospampinato** [comment]
> Results in:

The TypeScript type errors you can ignore, the actual error here seems "Error: ENOSPC: System limit for number of file watchers reached, watch 'src'" which I don't think I've ever hit personally, it sounds like you should raise some limits in your VM. 

Anyway watching files isn't strictly necessary for building cash, did the "/home/vagrant/xxtmp/cash/dist" directory get populated?

> Is that suitable? We'll implement the other utilities we need in DataTables itself.

Yes 👍

**Comment by DataTables** [comment]
Thank you - you are right, the build does indeed complete. I'd just assumed that it wasn't going to due to the TypeScript errors. And yes, the final error about the watch not bring able to run, a limit in my VM.

So all good here, happy to close of, or reuse for the TypeScript errors as you prefer.

**Comment by fabiospampinato** [comment]
Those TypeScript type errors are kind of intentional, almost all of them fundamentally are about potentially having the Window object in collections, guarding against that everywhere would make the library larger with no real benefit, as it's not common to by mistake have the Window object in a collection and not notice it, and adding type castings everywhere to silence TypeScript would make the code significantly uglier, so 🤷‍♂️
